### ISSUE TITLE
Synology NAS - converted AC3 audio cuts silent after a few mins

### ISSUE THREAD

**Issue by stmaro** [JakeWharton/mkvdts2ac3#111]
Hi, I am trying to get this installed on my Synology NAS 1513+ DSM 6. I got it installed as a post process for NZBGet, and it appears to work with no errors. However when I play the resulting file, the AC3 audio only has actual audio for a few mins. After that the sound goes silent and video keeps playing.

**Comment by matthewchubb** [comment]
Hey @stmaro did you get anywhere with this?

I'm still trying to get the script to run om my Synology 918+ (I have it working in windows) but struggling to get past the below errors on synology..

Would really appreciate your input.

Kind	Time	Text
INFO	Sun Oct 18 2020 12:31:13	Collection [MOVIE] added to history
ERROR	Sun Oct 18 2020 12:31:13	Post-process-script mkvdts2ac3.py for [MOVIE] failed (terminated with unknown status)
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: subprocess.CalledProcessError: Command '['/opt/bin/mkvinfo', '--ui-language', 'en', '/volume1/downloads/completed/[MOVIE]/bea356b9867d49ae81f3b80dc62c720d.mkv']' returned non-zero exit status 2
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: raise CalledProcessError(retcode, cmd, output=output)
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: output = subprocess.check_output([mkvinfo, "--ui-language", "en", ford])
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: File "/volume1/downloads/scripts/mkvdts2ac3.py", line 668, in process
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: process(os.path.join(ford, f))
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: File "/volume1/downloads/scripts/mkvdts2ac3.py", line 951, in <module>
INFO	Sun Oct 18 2020 12:31:12	mkvdts2ac3: Traceback (most recent call last):

**Comment by matthewchubb** [comment]
Hi choekstr,

Tried that but get a similar output;

Kind	Time	Text
INFO	Fri Oct 23 2020 11:18:07	Collection [MOVIE] added to history
ERROR	Fri Oct 23 2020 11:18:07	Post-process-script mkvdts2ac3.sh for [MOVIE] failed (terminated with unknown status)
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: subprocess.CalledProcessError: Command '['/opt/bin/mkvinfo', '--ui-language', 'en', '/volume1/downloads/completed/[MOVIE]/0f5a9495d24c483cafa0dda33339986e.mkv']' returned non-zero exit status 2
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: raise CalledProcessError(retcode, cmd, output=output)
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: output = subprocess.check_output([mkvinfo, "--ui-language", "en", ford])
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: File "/volume1/downloads/scripts/mkvdts2ac3.sh", line 668, in process
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: process(os.path.join(ford, f))
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: File "/volume1/downloads/scripts/mkvdts2ac3.sh", line 951, in <module>
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: Traceback (most recent call last):
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: filename: 0f5a9495d24c483cafa0dda33339986e.mkv
INFO	Fri Oct 23 2020 11:18:07	mkvdts2ac3: Processing file: /volume1/downloads/completed/[MOVIE]/0f5a9495d24c483cafa0dda33339986e.mkv
INFO	Fri Oct 23 2020 11:18:05	Executing post-process-script mkvdts2ac3.sh for [MOVIE]
INFO	Fri Oct 23 2020 11:18:05	Nothing to cleanup for [MOVIE]
INFO	Fri Oct 23 2020 11:18:05	Cleaning up [MOVIE]
INFO	Fri Oct 23 2020 11:18:05	Queueing [MOVIE] for post-processing
INFO	Fri Oct 23 2020 11:18:05	[MOVIE] returned from history back to download queue
INFO	Fri Oct 23 2020 11:18:05	Post-processing again [MOVIE]
